apiVersion: apps/v1
kind: Deployment
metadata:
  name: tournament
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tournament
  template:
    metadata:
      labels:
        app: tournament
    spec:
      containers:
        - name: tournament-container
          image: bvbacr.azurecr.io/tournament:1.0.0
          ports:
            - containerPort: 8083
          resources:
            requests:
              cpu: "50m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "1280Mi"
      imagePullSecrets:
        - name: acr-secret-bvb