variables:
  REGISTRY_USER: $CI_REGISTRY_USER
  REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD
  ACR: $CI_ACR

stages:
  - build
  - test
  - package
  - deploy

.auth-common:
  rules:
    - changes:
        - 'services/backend/authentication/**/*'

authentication-build:
  extends: .auth-common
  stage: build
  tags:
    - docker
  image: maven:3.9.6-eclipse-temurin-17-alpine
  script:
    - cd services/backend/authentication
    - mvn clean install

sonarqube-check:
  extends: .auth-common
  stage: test
  tags:
    - docker
  image: maven:3.9.6-eclipse-temurin-17-alpine
  script:
    - cd services/backend/authentication
    - mvn verify sonar:sonar -Dsonar.token=sqa_77a0622e343a4e64fa99581761d21a517d8cc906
  allow_failure: true
