apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication-container
          image: bvbacr.azurecr.io/authentication:1.0.3
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "150m"
              memory: "150Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      imagePullSecrets:
        - name: acr-secret-bvb