apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication-container
          image: bvbacr.azurecr.io/authentication:3.2.5-10514fe
          ports:
            - containerPort: 8081
      imagePullSecrets:
        - name: acr-secret-bvb