apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication-container
          image: bvbacr.azurecr.io/authentication:1.0.2
          ports:
            - containerPort: 8081
          resources:
            limits:
              memory: "200Mi"
              cpu: "0.1"
      imagePullSecrets:
        - name: acr-secret-bvb