stages:
  - build
  - test
  - package
  - security-scan
  - deploy

include:
  - local: '/services/backend/authentication/auth.gitlab-ci.yml'
  - local: '/services/backend/match/match.gitlab-ci.yml'
  - local: '/services/backend/post/post.gitlab-ci.yml'
  - local: '/services/backend/season/season.gitlab-ci.yml'
  - local: '/services/backend/team/team.gitlab-ci.yml'
  - local: '/services/backend/tournament/tournament.gitlab-ci.yml'
  - local: '/services/backend/user/user.gitlab-ci.yml'
  - local: '/services/backend/gateway/gateway.gitlab-ci.yml'