stages:
  - build
  - package
  - deploy

top-level-job:
  stage: build
  tags: 
  - shell
  script: 
    - echo "Hellow world..."

include:
  - local: '/services/backend/student/student.gitlab-ci.yml'
