stages:
  - build
  - test
  - package
  - security-scan
  - deploy

include:
  - local: '/services/backend/authentication/auth.gitlab-ci.yml'
  - local: '/services/backend/match/match.gitlab-ci.yml'
  - local: '/services/backend/post/post.gitlab-ci.yml'
  - local: '/services/backend/season/season.gitlab-ci.yml'
