stages:
  - build
  - test
  - deploy

top-level-job:
  stage: build
  tags: 
  - shell
  script: 
    - echo "Hellow world..."

include:
  - local: '/services/frontend/frontend.gitlab-ci.yml'
  - local: '/services/backend/school/school.gitlab-ci.yml'
  - local: '/services/backend/student/student.gitlab-ci.yml'
