spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tournament
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        connection:
          autocommit: false
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
  cloud:
    azure:
      servicebus:
        consumer:
          entity-name: deletetournament
        connection-string: Endpoint=sb://bvbforum.servicebus.windows.net/;SharedAccessKeyName=deletetournament-topicaccess;SharedAccessKey=e/zHZohQCUdlzmKZ74v9hfntFXyaINp0/+ASbMdDbAg=;EntityPath=deletetournament
      storage:
        blob:
          connection-string: DefaultEndpointsProtocol=https;AccountName=bvbforumblob;AccountKey=x4vEF+qO7qUizvObPyTbgyxeeCgAmFIMGO3mQa310w5glVjEk2bJx8mGwCcIx/KEM0yK9A4wyATR+AStr4sI+Q==;EndpointSuffix=core.windows.net
          container-name: tournaments-logo