apiVersion: apps/v1
kind: Deployment
metadata:
  name: post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      containers:
        - name: post-container
          image: bvbacr.azurecr.io/post:1.0.0
          ports:
            - containerPort: 8086
          resources:
            limits:
              memory: "777Mi"
              cpu: "0.1"
      imagePullSecrets:
        - name: acr-secret-bvb