spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowed-origins: "http://108.142.40.148"
            allowed-headers: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: season
          uri: http://season:8082
          predicates:
            - Path=/api/v1/season/**
          filters:
            - AuthFilter
        - id: tournament
          uri: http://tournament:8083
          predicates:
            - Path=/api/v1/tournament/protected/**
          filters:
            - AuthFilter
        - id: get-tournament
          uri: http://tournament:8083
          predicates:
            - Path=/api/v1/tournament/get/**
        - id: team
          uri: http://team:8084
          predicates:
            - Path=/api/v1/team/protected/**
          filters:
            - AuthFilter
        - id: get-team
          uri: http://team:8084
          predicates:
            - Path=/api/v1/team/get/**
        - id: match
          uri: http://match:8085
          predicates:
            - Path=/api/v1/match/protected/**
          filters:
            - AuthFilter
        - id: get-match
          uri: http://match:8085
          predicates:
            - Path=/api/v1/match/get/**
        - id: get-all-match
          uri: http://match:8085
          predicates:
            - Path=/api/v1/match/getall/**
        - id: post
          uri: http://post:8086
          predicates:
            - Path=/api/v1/post/protected/**
          filters:
            - AuthFilter
        - id: get-all-posts
          uri: http://post:8086
          predicates:
            - Path=/api/v1/post/get
        - id: authentication
          uri: http://authentication:8081
          predicates:
            - Path=/api/v1/auth/**
        - id: user
          uri: http://user:8087
          predicates:
            - Path=/api/v1/user/protected/**
          filters:
            - AuthFilter

application:
  security:
    jwt:
      secret-key: E91E158E4C6656F68B1B5D1C316766DE98D2AD6EF3BFB44F78E9CFCDF5