spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowed-origins: "http://localhost:4200"
            allowed-headers: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: season
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/season/**
          filters:
            - AuthFilter
        - id: tournament
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/tournament/**
          filters:
            - AuthFilter
        - id: team
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/team/**
          filters:
            - AuthFilter
        - id: match
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/match/**
          filters:
            - AuthFilter
        - id: authentication
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**

application:
  security:
    jwt:
      secret-key: E91E158E4C6656F68B1B5D1C316766DE98D2AD6EF3BFB44F78E9CFCDF5