apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway-container
          image: bvbacr.azurecr.io/gateway:1.0.4
          ports:
            - containerPort: 8222
          resources:
            requests:
              memory: "100Mi"
              cpu: "128m"
            limits:
              memory: "777Mi"
              cpu: "222m"
      imagePullSecrets:
        - name: acr-secret-bvb