stages:
  - build
  - test
  - sonarqube-check
  - deploy

.student-common:
  rules:
    - changes:
      - 'student/*'

student-build:
  extends: .student-common
  stage: build
  script: 
    - echo "Building student"

student-test:
  extends: .student-common
  stage: test
  script:
    - echo "Testing student"

test:
  stage: sonarqube-check
  tags:
    - docker
  image: docker:20.10.12
  services:
    - docker:20.10.12-dind
  variables:  # not strictly needed, depending on runner configuration
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
  script:
    - cd services/backend/student
    - docker-compose up

sonarqube-check:
  stage: sonarqube-check
  needs:
    - test
  tags: 
  - docker
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - cd services/backend/student
    - mvn verify sonar:sonar
  allow_failure: true
  only:
    - dev
