variables:
  REGISTRY_USER: $CI_REGISTRY_USER
  REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD
  ACR: $CI_ACR

stages:
  - build
  - test
  - package
  - deploy

.student-common:
  rules:
    - changes:
      - 'services/backend/student/**/*'

student-build:
  extends: .student-common
  stage: build
  tags:
    - docker
  image: maven:3.9.6-eclipse-temurin-17-alpine
  script:
    - cd services/backend/student
    - mvn compile

student-test:run-db:
  extends: .student-common
  stage: test
  tags:
    - docker
  image: docker:stable
  services:
    - name: docker:24.0-dind
  script:
    - cd services/backend/student
    - docker-compose --file="student.docker-compose.yml" up

student-test:run-test:
  extends: .student-common
  stage: test
  tags:
    - docker
  image: maven:3.9.6-eclipse-temurin-17-alpine
  script:
    - cd services/backend/student
    - mvn test 
    - docker-compose down

student-package:
  extends: .student-common
  stage: package
  tags:
    - docker
  image: maven:3.9.6-eclipse-temurin-17-alpine
  script:
    - cd services/backend/student
    - mvn package
  artifacts:
    paths:
      - target/*.jar

student-deploy:
  extends: .student-common
  stage: deploy
  tags:
    - docker
  image: docker:stable
  services:
    - name: docker:24.0-dind
  script:
    - cd services/backend/student
    - docker build -t student .
    - docker login $ACR -u $REGISTRY_USER -p $REGISTRY_PASSWORD
    - docker tag student $ACR/student
    - docker push $ACR/student
