apiVersion: apps/v1
kind: Deployment
metadata:
  name: team
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team
  template:
    metadata:
      labels:
        app: team
    spec:
      containers:
        - name: team-container
          image: bvbacr.azurecr.io/team:1.0.0
          ports:
            - containerPort: 8084
          resources:
            requests:
              memory: "448Mi"
              cpu: "125m"
            limits:
              memory: "896Mi"
              cpu: "250m"
      imagePullSecrets:
        - name: acr-secret-bvb