apiVersion: apps/v1
kind: Deployment
metadata:
  name: team
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team
  template:
    metadata:
      labels:
        app: team
    spec:
      containers:
        - name: team-container
          image: bvbacr.azurecr.io/team:1.0.0
          ports:
            - containerPort: 8084
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
      imagePullSecrets:
        - name: acr-secret-bvb