spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/team
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        connection:
          autocommit: false
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
  cloud:
    azure:
      #      servicebus:
      #        connection-string: Endpoint=sb://bvbforum.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=ermzS9oMHyIPua3lR4mQuSUaV8V5xFXjy+ASbI/3b1s=
      #        consumer:
      #          entity-type: topic
      #          entity-name: bvbforumtopic
      storage:
        blob:
          connection-string: DefaultEndpointsProtocol=https;AccountName=bvbforumblob;AccountKey=x4vEF+qO7qUizvObPyTbgyxeeCgAmFIMGO3mQa310w5glVjEk2bJx8mGwCcIx/KEM0yK9A4wyATR+AStr4sI+Q==;EndpointSuffix=core.windows.net
          container-name: teams-logo

