apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: bvbacr.azurecr.io/frontend:1.0.0
          ports:
            - containerPort: 4200
          resources:
            limits:
              memory: "777Mi"
              cpu: "0.1"
      imagePullSecrets:
        - name: acr-secret-bvb