apiVersion: apps/v1
kind: Deployment
metadata:
  name: match
spec:
  replicas: 1
  selector:
    matchLabels:
      app: match
  template:
    metadata:
      labels:
        app: match
    spec:
      containers:
        - name: match-container
          image: bvbacr.azurecr.io/match:1.0.0
          ports:
            - containerPort: 8085
          resources:
            requests:
              memory: "100Mi"
              cpu: "128m"
            limits:
              memory: "777Mi"
              cpu: "222m"
      imagePullSecrets:
        - name: acr-secret-bvb