apiVersion: apps/v1
kind: Deployment
metadata:
  name: match
spec:
  replicas: 1
  selector:
    matchLabels:
      app: match
  template:
    metadata:
      labels:
        app: match
    spec:
      containers:
        - name: match-container
          image: bvbacr.azurecr.io/match:1.0.0
          ports:
            - containerPort: 8085
          resources:
            requests:
              cpu: "50m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "1280Mi"
      imagePullSecrets:
        - name: acr-secret-bvb