spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/post
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        connection:
          autocommit: false
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none