apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user-container
          image: bvbacr.azurecr.io/user:1.0.0
          ports:
            - containerPort: 8087
          resources:
            limits:
              memory: "777Mi"
              cpu: "0.1"
      imagePullSecrets:
        - name: acr-secret-bvb